name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    name: ESLint & Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: |
          npm run lint 2>&1 | tee eslint-output.txt || {
            echo "ESLint found issues. Run 'npm run lint:fix' to auto-fix some issues."
            echo "::error::ESLint check failed. Please fix the linting issues and try again."
            exit 1
          }

      - name: Check code formatting with Prettier
        id: prettier
        run: |
          npm run format:check 2>&1 | tee prettier-output.txt || {
            echo "Code formatting issues detected. Run 'npm run format' to fix formatting."
            echo "::error::Prettier check failed. Please format your code and try again."
            exit 1
          }

      - name: Add workflow summary
        if: always()
        run: |
          echo "## Lint and Format Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ ${{ steps.eslint.outcome }} == "success" ]; then
            echo "✅ **ESLint**: All checks passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **ESLint**: Issues found - run \`npm run lint:fix\` to auto-fix" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ ${{ steps.prettier.outcome }} == "success" ]; then
            echo "✅ **Prettier**: Code formatting is correct" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Prettier**: Formatting issues found - run \`npm run format\` to fix" >> $GITHUB_STEP_SUMMARY
          fi